//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace freshMart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class customer_table
    {
        public int customer_id { get; set; }
        public string customer_username { get; set; }
        [EmailAddress]
        public string customer_email { get; set; }
        public string customer_password { get; set; }
        [Required(ErrorMessage = "Required")]
        [MinLength(11,ErrorMessage ="Mobile no should be 11 digit")]
        public string customer_contactNumber { get; set; }
    }
}
