//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace freshMart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class tbl_product
    {
        public int product_id { get; set; }
        [Required]
        public string product_name { get; set; }
        [Required]
        public string product_image { get; set; }
        
        public string product_description { get; set; }
        [Required]
        public int product_price { get; set; }
        public Nullable<int> product_fk_category { get; set; }
        public Nullable<int> product_fk_admin { get; set; }
    
        public virtual tbl_admin tbl_admin { get; set; }
        public virtual tbl_category tbl_category { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
